server:
  port: 8010
  context-path: /ha


spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/lijunnan?characterEncoding=utf8
    username: root
    password: root
    schema:
    dbcp2:
      max-wait-millis: 30000
      max-idle: 5
      min-idle: 5
      max-total: 10
      initial-size: 5
  data:
    mongodb:
      host: mongo-host
      port: 27017
      username: mongo
      password: Decobim!
      authentication-database: admin


application:
  product: springDemo







